name: ai_doc_scan
description: "AI powered doc scanner"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0
  share_plus: ^7.2.2
  permission_handler: ^11.3.0
  cunning_document_scanner: ^1.1.2
  gal: ^2.1.2 # <-- This is the correct, modern package.
  flutter_animate: ^4.5.2
  clipboard: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

